config/routes.rb
TrafficApp::Application.routes.draw do

  get "main" => "main#index" 
   get "log_in" => "users#login", :as => "log_in"  
  get "sign_up" => "users#new", :as => "sign_up"
    get "log_out" => "users#logout", :as => "log_out"  
  root :to => "users#new"  
  resources :users do    
    post 'process_login', :on => :collection 
 end

 root :to => 'main#index'

 match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
 class User < ActiveRecord::Base  
  attr_accessible :email, :password_hash, :password_salt, :password, :password_confirmation

  attr_accessor :password,:password_confirmation

  before_save :encrypt_password  

  validates_confirmation_of :password

  validates_presence_of :password, :on => :create

  validates_presence_of :email

  validates_uniqueness_of :email

  def encrypt_password

    if password.present?

      self.password_salt = BCrypt::Engine.generate_salt

      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)

    end  

  end 
	def self.authenticate(email, password)  
    user = find_by_email(email)  
		if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)  
      user  
		end   
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/current_controller.rb
class CurrentController < ApplicationController

require 'open-uri'

	def index
		url= ["http://hatrafficinfo.dft.gov.uk/feeds/datex/England/CurrentRoadworks/content.xml","http://hatrafficinfo.dft.gov.uk/feeds/datex/England/UnplannedEvent/content.xml","http://hatrafficinfo.dft.gov.uk/feeds/datex/England/CurrentPlanned/content.xml"]
		array1=[]
		array2=[]
		array3=[]
		array4=[]
		url.each do |set|
		@doc = Nokogiri::HTML(open(set))
		#doc = Nokogiri::XML(open(set))
		@doc.xpath("//comment/value").each do |link|
		result = (link.to_s).gsub!(/<value lang="en">/, "")
		array1.push(result.gsub!(/<\/value>/, ""))
		end
		@doc.xpath("//delays").each do |link|
		result = (link.to_s).gsub!(/<delays>/, "")
		result = result.gsub!(/<\/delays>/, "")
		result = result.gsub!(/<delaytimevalue>/, "")
		result = result.gsub!(/<\/delaytimevalue>/, "")
		array2.push((result.to_i)/60)
		end
		@doc.xpath("//validperiod/startofperiod").each do |link|
		result = (link.to_s).gsub(/<startofperiod>/, " From ")
		result = result.gsub(/<\/startofperiod>/, "")
		result = result.gsub(/T/, "  ")
		result = result.gsub(/[Z]/, "")
		array3.push(result)
		end
		@doc.xpath("//validperiod/endofperiod").each do |link|
		result = (link.to_s).gsub(/<endofperiod>/, "")
		result = result.gsub(/<\/endofperiod>/, "")
		result = result.gsub(/T/, "  ")
		result = result.gsub(/[Z]/, "")
		array4.push(result)
		end
		end
		@description = array1
		@delay = array2
		@period = array3
		@end = array4
		if session[:user_id] != nil
			@user = User.find(session[:user_id]).email
		else
			@user = "Guest"
		end
	end
	def search
		url= ["http://hatrafficinfo.dft.gov.uk/feeds/datex/England/CurrentRoadworks/content.xml","http://hatrafficinfo.dft.gov.uk/feeds/datex/England/UnplannedEvent/content.xml","http://hatrafficinfo.dft.gov.uk/feeds/datex/England/CurrentPlanned/content.xml"]
		array1=[]
		url.each do |set|
		@doc = Nokogiri::HTML(open(set))
		@doc.xpath("//comment/value").each do |link|
		result = (link.to_s).gsub!(/<value lang="en">/, "")
		result = result.gsub!(/<\/value>/, "")
		if result.include?(params[:key]) == true
			array1.push(result)
		end
		end
		end
		if array1.nil? == true
			@finding = ["There were no results for your query","Try again next time"]
			else
			@finding = array1
		end
		if session[:user_id] != nil
			@user = User.find(session[:user_id]).email
		else
			@user = "Guest"
		end
	end
end

app/controllers/future_controller.rb
class FutureController < ApplicationController

require 'open-uri'

	def index
		url= ["http://hatrafficinfo.dft.gov.uk/feeds/datex/England/FuturePlanned/content.xml","http://hatrafficinfo.dft.gov.uk/feeds/datex/England/FutureRoadworks/content.xml"]
		array1=[]
		array2=[]
		array3=[]
		array4=[]
		url.each do |set|
		@doc = Nokogiri::HTML(open(set))
		#doc = Nokogiri::XML(open(set))
		@doc.xpath("//comment/value").each do |link|
		result = (link.to_s).gsub!(/<value lang="en">/, "")
		array1.push(result.gsub!(/<\/value>/, ""))
		end
		@doc.xpath("//delays").each do |link|
		result = (link.to_s).gsub!(/<delays>/, "")
		result = result.gsub!(/<\/delays>/, "")
		result = result.gsub!(/<delaytimevalue>/, "")
		result = result.gsub!(/<\/delaytimevalue>/, "")
		array2.push((result.to_i)/60)
		end
		@doc.xpath("//validperiod/startofperiod").each do |link|
		result = (link.to_s).gsub(/<startofperiod>/, " From ")
		result = result.gsub(/<\/startofperiod>/, "")
		result = result.gsub(/T/, "  ")
		result = result.gsub(/[Z]/, "")
		array3.push(result)
		end
		@doc.xpath("//validperiod/endofperiod").each do |link|
		result = (link.to_s).gsub(/<endofperiod>/, "")
		result = result.gsub(/<\/endofperiod>/, "")
		result = result.gsub(/T/, "  ")
		result = result.gsub(/[Z]/, "")
		array4.push(result)
		end
		end
		@description = array1
		@delay = array2
		@period = array3
		@end = array4
		if session[:user_id] != nil
			@user = User.find(session[:user_id]).email
		else
			@user = "Guest"
		end
	end
	def search
		url= ["http://hatrafficinfo.dft.gov.uk/feeds/datex/England/FuturePlanned/content.xml","http://hatrafficinfo.dft.gov.uk/feeds/datex/England/FutureRoadworks/content.xml"]
		array1=[]
		url.each do |set|
		@doc = Nokogiri::HTML(open(set))
		@doc.xpath("//comment/value").each do |link|
		result = (link.to_s).gsub!(/<value lang="en">/, "")
		result = result.gsub!(/<\/value>/, "")
		if result.include?(params[:key]) == true
			array1.push(result)
		end
		end
		end
		if array1.nil? == true
			@finding = ["There were no results for your query"]
			else
			@finding = array1
		end
				if session[:user_id] != nil
			@user = User.find(session[:user_id]).email
		else
			@user = "Guest"
		end
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

require 'open-uri'

	def index
		if session[:user_id] != nil
			@user = User.find(session[:user_id]).email
		else
			@user = "Guest"
		end
	end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController  
  
    def new  
      @user = User.new  
    end 

    def create  
      @user = User.new(params[:user])  
      if @user.save  
        redirect_to :sign_up, :notice => "User Created."  
      else  
        render "new"  
      end  
    end 
	  def login  
  
  end  
      
  def process_login  

    user = User.authenticate(params[:email], params[:password])  
  
   if user  
    
      session[:user_id] = user.id  
    
      redirect_to :main, :notice => "Logged in!"  
    
   else  
   
      flash.now.alert = "Invalid email or password"  
   
      render "login"  
   
    end  

  end  
  
def logout
  session[:user_id] = nil
  redirect_to :main , :notice => "Logged out!"
end 

 
   
  end  

app/helpers/application_helper.rb
module ApplicationHelper
	def current_roadworks
	
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/current/index.html.erb
<body style="background-color:#CFCFCF;">
	<div id="body" align="center" style="width:100%;height:100%;position:relative" >
		<h1>Current road problems</h1>
		<div style="FLOAT:left;position:relative;width:33%;height:100%">
			<% @description.each do |description| %>
			<div style="border:2px solid black;height:200px">
				Description:<%= description =%><p>
			</div>
			<% end %>
		</div>
		<div style="FLOAT:left;position:relative;width:17%;height:100%">
			<% @period.each do |period| %>
			<div style="border:2px solid black;height:200px">
				<%= period =%><p>
			</div>
			<% end %>
		</div>
		<div style="FLOAT:left;position:relative;width:17%;height:100%">
			<% @end.each do |period| %>
			<div style="border:2px solid black;height:200px">
				End:<%= period =%><p>
			</div>
			<% end %>
		</div>
		<div style="FLOAT:left;position:relative;width:33%;height:100%">
			<% @delay.each do |delay| %>
			<div style="border:2px solid black;height:200px">
				Delays:<%= delay =%> minutes<p>
			</div>
			<% end %>
		</div>
		<br/>
	</div>
	<div>
		<h3>Search</h3>
		<form action ="search" method="post">
		<input name = "key" type="input" />
		<input value="Send" type="submit"/>
		</form> 
		<%= link_to "Back to main page", "/main/index" %><p>  
		<%= link_to "Future", "/future/index" %>
	</div>
	<div align="right">
		You are logged in as <%= @user %>
		<%= link_to 'Admin Log In', log_in_path %>
		<%= link_to 'Log out', log_out_path %>
	</div>
</body>

app/views/current/search.html.erb
<body style="background-color:#CFCFCF;">
	<div id="body" align="center" style="width:100%;height:100%;position:relative" >
		<h1>Search results</h1>
		<div style="FLOAT:left;position:relative;width:100%;height:100%">
			<% @finding.each do |description| %>
			<div style="border:2px solid black;height:200px">
				<%= description =%><p>
			</div>
			<% end %>
		</div>
		<br/>
	</div>
	<div>
		<%= link_to "Back to main page", "/main/index" %><p>  
		<%= link_to "Back to the Present", "/current/index" %>
	</div>
</body>

app/views/future/index.html.erb
<body style="background-color:#CFCFCF;">
	<div id="body" align="center" style="width:100%;height:100%;position:relative" >
		<h1>Road Problems from the Future</h1>
		<div style="FLOAT:left;position:relative;width:33%;height:100%">
			<% @description.each do |description| %>
			<div style="border:2px solid black;height:200px">
				Description:<%= description =%><p>
			</div>
			<% end %>
		</div>
		<div style="FLOAT:left;position:relative;width:17%;height:100%">
			<% @period.each do |period| %>
			<div style="border:2px solid black;height:200px">
				Start:<%= period =%><p>
			</div>
			<% end %>
		</div>
		<div style="FLOAT:left;position:relative;width:17%;height:100%">
			<% @end.each do |period| %>
			<div style="border:2px solid black;height:200px">
				End:<%= period =%><p>
			</div>
			<% end %>
		</div>
		<div style="FLOAT:left;position:relative;width:33%;height:100%">
			<% @delay.each do |delay| %>
			<div style="border:2px solid black;height:200px">
				Delays:<%= delay =%> minutes<p>
			</div>
			<% end %>
		</div>
		<br/>
	</div>
	<div>
	<h3>Search</h3>
<form action ="search" method="post">
<input name = "key" type="input" />
<input value="Send" type="submit"/>
</form> 
		<%= link_to "Back to main page", "/main/index" %><p>  
		<%= link_to "Current", "/current/index" %>
	</div>
		<div align="right">
		You are logged in as <%= @user %>
		<%= link_to 'Admin Log In', log_in_path %>
		<%= link_to 'Log out', log_out_path %>
	</div>
</body>

app/views/future/search.html.erb
<body style="background-color:#CFCFCF;">
	<div id="body" align="center" style="width:100%;height:100%;position:relative" >
		<h1>Search results</h1>
		<div style="FLOAT:left;position:relative;width:100%;height:100%">
			<% @finding.each do |description| %>
			<div style="border:2px solid black;height:200px">
				<%= description =%><p>
			</div>
			<% end %>
		</div>
		<br/>
	</div>
	<div>
		<%= link_to "Back to main page", "/main/index" %><p>  
		<%= link_to "Back to the Future", "/future/index" %>
	</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPEhtml>
<html>
<head>
<% if content_for?(:head) %>
	<%= content_for(:head) %>
<% else %>
	<title>Road app</title>
<% end %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%flash.each do|name,msg|%>
<%=content_tag :div,msg,:id=>"flash#{name}"%>

<%end%>
<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<html>
	<head>
		<title>App</title>
	</head>

	<body style="background-color:#CFCFCF;">

		<div id="body" align="center" >

		<div id="text">
		<h2>Welcome to road app, the completely usefull app that tells you things!</h2>
		<p>
		The idea behind road app is to take real time open data about travel disruption supplied by the government, and display it here in
		a convient mannier, so you can plan your journeys around them. Currently the information that we take is supplied in two formats, present and future, which
		caters to current roadworks, events and accidents(present), and of course planned roadworks and events(future).<br/>
		The data is maintained by the highways agency and can be found <a href="http://data.gov.uk/dataset/live-traffic-information-from-the-highways-agency-road-network">here</a>,
		along with live traffic data.<p></div>
		You can search this data through a form at the bottom of either page, e.g. "M24" which will return all data sets mentioning M24. Beware, searching for A5 will return
		results for A5, A52, A55 etc. but thats life. If you possess an admin account you can also log in with that.
		<h3>
		<div><%= link_to "Current", "/current/index" %></div>
		<div><%= link_to "Future", "/future/index" %></div>
		<br>
		</h3>
		<br/>
		</div>
		<div align="right">
			You are logged in as <%= @user %>
			<%= link_to 'Admin Log In', log_in_path %>
			<%= link_to 'Log out', log_out_path %>
		</div>
	</div>
	</body>
</html>

app/views/users/login.html.erb

<h1>Log in</h1>
<%= form_tag :action => 'process_login' %>
<p>
<%= label_tag :UserName %><br />
<%= text_field_tag :email, params[:email] %>
</p>
<p>
<%= label_tag :password %><br />
<%= password_field_tag :password %>
</p>

<%= submit_tag "log in"%>

app/views/users/new.html.erb
<h1>Sign Up</h1>  

  <%= form_for @user do |f| %>  

  <% if @user.errors.any? %>  

    <div class="error_messages">  

      <h2>Form is invalid</h2>  

      <ul>  

        <% for message in @user.errors.full_messages %>  

          <li><%= message %></li>  

        <% end %>  

      </ul>  

    </div>  

  <% end %>  

  <p>  

    <%= f.label :UserName %><br />  

    <%= f.text_field :email %>  

  </p>  

  <p>  

    <%= f.label :password %><br />  

    <%= f.password_field :password %>  
	
</p>  

  <p>  

    <%= f.label :password_confirmation %>  

    <%= f.password_field :password_confirmation %>  

  </p>  

  <p class="button"><%= f.submit %></p>  

<% end %> 